version: "3"

services:
  nats:
    image: nats:latest
    command:
      - "-js"
    ports:
      - "127.0.0.1:4222:4222"

  toxicproxy:
    image: shopify/toxiproxy:latest
    network_mode: "host"

  memcached:
    image: memcached:latest
    ports:
      - "127.0.0.1:11211:11211"

  redis:
    image: redis:6
    ports:
      - "127.0.0.1:6379:6379"

  redis2:
    image: redis:6
    ports:
      - "127.0.0.1:6378:6379"

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-west-1
      - EDGE_PORT=9324
      - SERVICES=sqs
    ports:
      - '127.0.0.1:9324:9324'

  beanstalk:
    build:
      context: .
      dockerfile: Dockerfile-beanstalkd.yaml
    ports:
      - "127.0.0.1:11300:11300"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"

  postgresql:
    container_name: temporal-postgresql
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    ports:
      - "5432:5432"

  rabbitmq_slow:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    ports:
      - "127.0.0.1:15673:15672"
      - "127.0.0.1:5673:5672"

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:latest
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    ports:
      - "7233:7233"

  temporal-web:
    container_name: temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:latest
    ports:
      - "8088:8088"

  temporal-admin-tools:
    container_name: temporal-admin-tools
    image: temporalio/admin-tools:latest
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true