version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"

  rabbitmq_slow:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    ports:
      - "127.0.0.1:15673:15672"
      - "127.0.0.1:5673:5672"
