version: "3.8"

services:
  nats:
    image: nats:latest
    command:
      - "-js"
    ports:
      - "127.0.0.1:4222:4222"
    networks:
      jobs:

  toxicproxy:
    image: shopify/toxiproxy:latest
    network_mode: "host"

  beanstalk:
    build:
      context: .
      dockerfile: Dockerfile-beanstalkd.yaml
    ports:
      - "127.0.0.1:11300:11300"
    networks:
      jobs:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
    networks:
      jobs:

  rabbitmq_slow:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "127.0.0.1:15673:15672"
      - "127.0.0.1:5673:5672"
    networks:
      jobs:

networks:
  jobs:
    name: jobs
