version: "3.8"

services:
  nats:
    image: nats:latest
    command:
      - "-js"
    ports:
      - "127.0.0.1:4222:4222"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

networks:
  nats:
    name: nats